export const CREATE_ACCOUNT = `[Auth] CREATE_ACCOUNT`;
export const CREATE_ACCOUNT_SUCCESS = `${CREATE_ACCOUNT}_SUCCESS`;
export const CREATE_ACCOUNT_FAILURE = `${CREATE_ACCOUNT}_FAILURE`;
export const CREATE_ACCOUNT_CANCELLED = `${CREATE_ACCOUNT}_CANCELLED`;

export const GET_AUTH_DATA = '[Auth] GET_AUTH_DATA';
export const GET_AUTH_DATA_SUCCESS = '[Auth] GET_AUTH_DATA_SUCCESS';
export const GET_AUTH_DATA_FAILURE = '[Auth] GET_AUTH_DATA_FAILURE';

export const TRY_LOG_IN = '[Auth] TRY_LOG_IN';
export const LOG_IN_SUCCESS = '[Auth] LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = '[Auth] LOG_IN_FAILURE';
export const CANCEL_LOG_IN = '[Auth] CANCEL_LOG_IN';