module.exports = {
  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_MIN_LENGTH: 'USERNAME_MIN_LENGTH',
  USERNAME_MAX_LENGTH: 'USERNAME_MIN_LENGTH',

  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_MIN_LENGTH: 'EMAIL_MIN_LENGTH',
  EMAIL_MAX_LENGTH: 'EMAIL_MAX_LENGTH',
  
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH: 'PASSWORD_MIN_LENGTH',
  PASSWORD_MAX_LENGTH: 'PASSWORD_MAX_LENGTH',

  USER_EXISTS: 'USER_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS'
}